# Generated by Django 6.0.4 on 2026-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relational_app', '0002_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserinfomodel',
            name='user_type',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=20, null=True),
        ),
    ]
